### ISSUE TITLE
Doesn't work with `Git Bash for Windows`

### ISSUE THREAD

**Issue by sledgehammer999** [transifex/cli#184]
The cli tool doesn't work with `Git Bash for Windows`.
Tested versions: 1.6.5, 1.6.7

Issuing a command like
```
./tx status project.resource
```

results in:
```
# Gathering data for resources
could not find resource 'project.resource' in local configuration
```

while it works if I run it from a Windows Command Prompt.

**Comment by codegaze** [comment]
Hello @sledgehammer999,

we testing on a windows machine with `Git Bash for Windows` and we had the expected behaviour.

Could you please share a bit more about your config file, maybe the real (or similar without sensitive data) `project.resource` in case there is a character that creates the unusual behaviour?

**Comment by sledgehammer999** [comment]
The config file is this: https://github.com/qbittorrent/qBittorrent/blob/master/.tx/config

I just tried (from the root of the git repo):
```
./tx.exe status qbittorrent.qbittorrentdesktop
```

and I get the error I mentioned in my first post.

**Comment by sledgehammer999** [comment]
Hmm, if I try the `qbittorrent.qbittorrentdesktop_master` ID it works. The ID `qbittorrent.qbittorrent_master` doesn't work either.

**Comment by sledgehammer999** [comment]
I tried it again today and it worked. I used v1.6.7.
I don't know if the new version fixed it or if something was previously borked with my environment.
