### ISSUE TITLE
tx migrate command requires token which can be avoided

### ISSUE THREAD

**Issue by awais786** [transifex/cli#29]
Right now `tx migrate` command requires token. But apparently it just make changes in config files. 
May be this can be make optional ?

**Comment by codegaze** [comment]
Hello @awais786, 

The reasoning behind asking for a token is: 

* Migrate the current `config` file with the new resource id's so that the user doesn't do it manually. In order to do that, we need to retrieve each resource's organisation slug.
* We need to make sure if someone has a `.transifexrc` file, they have the correct settings (api token) and not the username/password cases of the old API, if there are any.

We are happy to answer, in case you have any more questions :)

**Comment by awais786** [comment]
Thanks for clarity.
