### ISSUE TITLE
Please add a --silent flag to reduce the clutter in CI/CD environments

### ISSUE THREAD

**Issue by fjaeger** [transifex/cli#30]
I really like the CLI progress animation that you added with the new CLI, **but** in a CI/CD environment, the new output simply does not help. It would be nice if there was some kind of toggle to have a more compact output of the progress. Without any fancy animation or similar. Just print the currently active step and that's it :)

**Comment by codegaze** [comment]
Hey @fjaeger,

We appreciate the feedback! 
This sounds very reasonable and we probably missed that during implementation.

We are currently re-evaluating a bit the "fancy" output of the CLI, so we need some time for this, but it's going to be addressed in a future release.

**Comment by codegaze** [comment]
Hey @fjaeger , this should be fixed in the latest version of the CLI [v1.2.0](https://github.com/transifex/cli/releases/tag/v1.2.0). The output on this version should be simplified and less noisy.

Feel free to try it out, provide feedback and/or close this issue! :)

**Comment by terencehonles** [comment]
I was just updating us from the legacy client and running this locally my screen jumps around in a funny manner. I'm not sure if this is an issue because I'm running this in tmux or some other issue, but it's definitely strange and I'd _prefer_ it not do that, but it's not that big of a deal.

**Comment by mathaeus** [comment]
I'm currently testing CLI `1.2.0`. 

@codegaze it would be very good if there was an option to reduce the output to a minimum or make it silent altogether.
We have quite a few resources and for various reasons we are pulling them all at once usually and on our CI we are running into the problem that already after a few minutes we run into the "maximum allowed size of the log file" (100MB!)

<img width="996" alt="transifex_logs" src="https://user-images.githubusercontent.com/5389635/176424760-10ecdfe8-f23a-4150-aaa1-3ed686e70d33.png">

**Comment by kbairak** [comment]
@mathaeus  TL;DR There is a chance that appending `| cat` to the tx command in your CI configuration file could solve the problem, but I am not 100% sure.

Explanation:

Because of parallelism, we have implemented some sort of "real-time" output. We use a third-party library for this, but I assume this works by printing a chunk of text to the terminal and then, for each update, send a bunch of backspace symbols and print the whole chunk again. If something were to capture the output, both the initial chunk, the backspaces and the updated chunks would be captured.

Because we anticipated that this could cause problems with CI environments and log files, the tx client will detect if it's currently sending its output to a terminal or not and, if not, simply print new lines instead of re-printing the whole chunk. Appending `| cat` to the command will tell the tx client that it is not printing to a terminal. So, for example:

```
tx push ...

    pushing -> pushed

tx push ...  | cat

    pushing
    pushed
```

(You can imagine that the arrow means that the text is replaced by the new message)

Our initial assumption was that CI environments that keep a log of what's happening would make the tx client think it is **not** printing to a terminal but perhaps they have found a way to both make it think that it **is** printing to a terminal **and** capture its output at the same time.

Please try this out and let us know if it works. If this is indeed the solution, we will consider adding a `--silent` flag or something similar that will have the same effect as appending `| cat` to the command, ie make the tx client always think it is **not** printing to a terminal.

**Comment by mathaeus** [comment]
Hi @kbairak, thanks for the tip.

I tried it out, and it indeed seems to reduce the noise. At least to such a degree that we are not running into the maximum space of the log file 👍 

Please see below what the log now looks for us. 
**I'd look at that info as "verbose information" that we could ideally also silence, what do you think?** 
I could imagine that logging way less would speed up the execution as well.

<img width="741" alt="Screenshot 2022-06-30 at 17 24 49" src="https://user-images.githubusercontent.com/5389635/176716505-671631c5-d3fa-482b-8db6-7392da743685.png">
