### ISSUE TITLE
An error with `tx push -s`

### ISSUE THREAD

**Issue by mendax1234** [transifex/cli#41]
![image](https://user-images.githubusercontent.com/62934294/162883879-adcd1662-adc2-44f8-a68c-2082e7d1d101.png)
How to fix it?

**Comment by codegaze** [comment]
Hey @mendax1234 from what I understand from your screenshot, [this is](https://github.com/transifex/transifex-client/issues) where you want to create an issue which is the python version of our client.  

This repo is related to the new version of the client.

**Comment by mendax1234** [comment]
So , the client can't suit python 3.10 version?

**Comment by codegaze** [comment]
I believe the python client is up to 3.9 version, but the people in that repo can provide a more solid answer, since this client is built in Go. 
My suggestion would be to migrate to this version of the client since the old one will sunset on Nov 2022. Feel free to check the [readme](https://github.com/transifex/transifex-client/issues) for more information.

**Comment by mendax1234** [comment]
Thanks, l have installed python 3.9 and know the transifex seems to work perfectly!
