### ISSUE TITLE
Unable to use tx add remote

### ISSUE THREAD

**Issue by jordimas** [transifex/cli#90]
Hello

tx version 1.3.1

I have been unable to usse the "tx add remote" option.

I do:

_tx init
tx add remote --file-filter 'translations/<project_slug>.<resource_slug>/<lang>.<ext>' "https://www.transifex.com/projects/p/yumex"_

And I get always the error:

_unable to fetch project: Get "/projects/o:projects:p:p": unsupported protocol scheme ""_

Am I doing something wrong? Thanks

**Comment by kbairak** [comment]
Hey @jordimas ,

The URL structure you are using is old. I am guessing you copy-pasted it from a script that used to work with the old client. The correct one is: `https://www.transifex.com/timlau/yumex`.

Give it a try and please let us know how it goes.

Thanks!

**Comment by jordimas** [comment]
Thanks @kbairak 

My script now looks like with the update project URL:

tx init
tx add remote --file-filter 'translations/<project_slug>.<resource_slug>/<lang>.<ext>' "https://www.transifex.com/timlau/yumex"

and I get the error:

_unable to fetch project: Get "/projects/o:timlau:p:yumex": unsupported protocol scheme ""_

Any idea?

Thanks

**Comment by kbairak** [comment]
Hey @jordimas,

I cannot figure out what the problem is with the information at hand (yet). My best guess is that a `.tx/config` and/or a `~/.transifexrc` file already exists and the URL for the API host is not correct. Is it possible for you to paste the contents of these 2 files here?

**BE CAREFUL!!!** The `~/.transifexrc` file contains API tokens and/or passwords. Make sure you remove them before pasting here.

**Comment by jordimas** [comment]
Thanks. 

I had an old ~/.transifexrc which did not contain the _rest_hostname_ field. As I added this line:

_rest_hostname = https://rest.api.transifex.com_

I worked. 

May be it will be worth to give an error message if _rest_hostname_ is not defined.
